version: "3"
services:   
  api:
    image: api-dev:latest
    build:
      context: ./backend
      args:
        CURRENT_ENVIRONMENT: dev
        PORT: 8080
    volumes:
      - ./backend:/app
  client:
    image: client-dev:latest
    build:
      context: ./client
      dockerfile: Dockerfile.dev
  proxy:
    image: proxy-dev:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8081:80"
      
