version: "3"
services:   
  client:
    image: client-dev:latest
    build:
      context: ./client
      dockerfile: Dockerfile.dev
  proxy:
    image: proxy-dev:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8081:80"
      
